### ISSUE TITLE
multiple ledgers

### ISSUE THREAD

**Issue by cauerego** [bradyt/cone#80] opened 2021-07-05 15:54 UTC
could you please add a feature to allow multiple files to be opened at the same time? or at least some easier way to swap. 😁

**Comment by bradyt** [comment] 2021-07-06 00:20
Closing as this seems to be a duplicate of https://github.com/bradyt/cone/issues/69. Let me know if I missed something.

Please don't use "lowercase style" uniformly everywhere on this issue tracker. I personally find it harder to read, and the posts are fairly persistent and read many times.

**Closed** 2021-07-06 00:20 UTC
Labels: multiple files

**Comment by cauerego** [comment] 2021-07-06 03:03
can't promise anything! 🤣

what do you mean by "uniformly" and "fairly persistent"?

"harder to read" is just a matter of conditioning.

but i should, anyway, use smaller paragraphs! 😘

**Comment by bradyt** [comment] 2021-07-06 07:27
I am struggling to perform this interaction efficiently. Unfortunately, I've decided to explore Github's block feature. Just wanted to be up front about it. Apologies it came to that. I'll consider removing the block when I have more time for discussion of this project with you.
