### ISSUE TITLE
Setting Locale not working

### ISSUE THREAD

**Issue by Aquan1412** [bradyt/cone#42] opened 2019-09-28 18:03 UTC
It seems the new locale setting is not working as intended. While changing it does change the UI for adding a transaction, the main view is not affected. Maybe its using the "global" locale of the smartphone?

In my case my global language setting for my phone is german, but for my ledger I use the british/american notation. Since the new setting was introduced, all new transactions used the german notation, regardless of the locale setting in the app. 

Also, when I change the locale setting to "en", the new postings are wrong since apparently the wrong decimal separator is used (a posting of €75.95 gets turned into €7595,00). When I use "de" locale, this doesn't happen.

**Comment by bradyt** [comment] 2019-09-28 22:28
Thank you for the report, and apologies for the bug.

I think you've understood the intended behavior correctly, despite it being strange and not well-documented. The numberLocale is just there to help pad zeros for data entry, so user can type "1" and it automatically is written as "1.00", or "1,00", according to their numberLocale (or just "1" in the case of for example "JPY" currency name). And just to be clear, it should not round.

#### Reproduce

I hope the following description is considered the same as your issue?

If I set system locale to "de", and cone's "numberLocale" to "en", then the settings example shows "5.00", but in addTransaction, hint is "0,00", and field input "75.95" gets written to file as "7595,00".

#### Possible fixes

Using `rgrep` to search for "locale" and "hint", I think it is a failure to use numberLocale in formatTransaction, as well as in hintText.

I don't know when in the next few days I can stop to look at this, and try to fix it carefully, but I suspect I just need to use numberLocale in formatTransaction, and padZeros (with numberLocale) in hintText.

**Comment by bradyt** [comment] 2019-09-30 00:23
This is fixed in v0.2.17+25, is on Google Play, and should be on F-Droid within a few days.

I'll close this for now, but please let me know if I missed something, we can reopen.

Thank you!

**Closed by bradyt** 2019-09-30 00:23 UTC
Labels: bug, formatting, next
