### ISSUE TITLE
F-Droid releases have fallen behind

### ISSUE THREAD

**Issue by alerque** [bradyt/cone#61] opened 2020-02-20 17:25 UTC
I just noticed that there seems to be a lot of development activity I've missed recently because I have an F-Droid install not Play.

**Comment by bradyt** [comment] 2020-02-20 18:39
@alerque Issue template requested version, can you provide?

**Comment by alerque** [comment] 2020-02-20 18:47
F-Droid is showing: 0.2.18
Play is showing: 0.2.20

(And issue templates don't show up when opening issues from apps such as FastHub.)

**Comment by bradyt** [comment] 2020-02-20 18:54
I don't know when I'll get to the F-Droid issue. Further analysis is welcome.

**Comment by bradyt** [comment] 2020-02-22 22:07
Issue opened at https://gitlab.com/fdroid/fdroiddata/issues/1957. Currently there is an open merge request linked from that issue.

**Comment by bradyt** [comment] 2020-02-24 01:11
Closed as duplicate of https://gitlab.com/fdroid/fdroiddata/issues/1957.

**Closed by bradyt** 2020-02-24 01:11 UTC

**Comment by alerque** [comment] 2020-03-13 08:49
0.2.20 came across F-Droid today, so it looks like this got fixed.
